[package]
name = "calamine"
version = "0.18.0"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
repository = "https://github.com/tafia/calamine"
documentation = "https://docs.rs/calamine"
description = "An Excel/OpenDocument Spreadsheets reader and deserializer in pure rust"
license = "MIT"
readme = "README.md"
keywords = ["excel", "vba", "office", "ods", "serde"]
categories = ["encoding", "parsing", "text-processing"]
exclude = ["tests/**/*"]
edition = "2018"

[badges]
travis-ci = { repository = "tafia/calamine" }
appveyor = { repository = "tafia/calamine" }

[dependencies]
byteorder = "1.3.4"
codepage = "0.1.1"
encoding_rs = "0.8.24"
log = "0.4.11"
serde = "1.0.116"
quick-xml = { version = "0.19", features = ["encoding"] }
zip = { version = "0.5.8", default-features = false, features = ["deflate"] }
chrono = { version = "0.4.17", features = ["serde"], optional = true }

[dev-dependencies]
glob = "0.3"
env_logger = "0.7"
serde_derive = "1.0.116"

[features]
default = []
dates = ["chrono"]
